# action.yml
name: 'Build 4D'
author: 'Eric Marchand'
branding:
  icon: 'package'
  color: 'blue'
description: 'Build 4D code'
inputs:
  project:
    description: 'Project to build'
    required: false
  compilation-options:
    description: "Some additional compilation options"
    required: false
    default: "{}"
  product-line:
    description: 'tool4d product line'
    required: false
    default: "20.x"
  version:
    description: 'tool4d version'
    required: false
    default: "20.0"
  build:
    description: 'tool4d build number'
    required: false
    default: "latest"
runs:
  using: 'composite'
  steps:
    - id: setup
      name: Setup environment 
      shell: bash
      run: |
        WORKINK_DIRECTORY="${{ github.workspace }}"
        WORKINK_DIRECTORY=$(echo $WORKINK_DIRECTORY|sed -e 's/\\/\\\\/g') # escape workspace for json
        echo "WORKINK_DIRECTORY=$WORKINK_DIRECTORY" >> $GITHUB_ENV
    - id: tool4d
      uses: e-marchand/tool4d-action@v1
      env:
        GITHUB_THIS_ACTION_PATH: ${{ github.action_path }}
      with:
        product-line: "${{ inputs.product-line }}"
        version: "${{ inputs.version }}"
        build: "${{ inputs.build }}"
        project: "${{env.GITHUB_THIS_ACTION_PATH}}/Project/actions.4DProject"
        user-param: '{"path": "${{ inputs.project }}", "workingDirectory": "${{ env.WORKINK_DIRECTORY }}", "options": "${{ inputs.compilation-options }}"}'
        startup-method: main
        error-flag: "${{env.GITHUB_THIS_ACTION_PATH}}/error"
